# Generated by Django 2.2.7 on 2019-11-11 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=140)),
                ('date_created', models.DateField()),
                ('date_edited', models.DateField()),
                ('delete', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='twitterprojectapp.User')),
            ],
        ),
    ]
